spring.application.name=proyecto-final-ecom-fs
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=Root
cloudinary.cloud_name=dm0nmdo1s
cloudinary.api_key=765694142536268
cloudinary.api_secret=13jlNVWoZ-nHJJXPMduvHz_NPQk
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format-sql=true

